# Configuration for this blog, it's in TOML:
# https://github.com/mojombo/toml


# the server's root-path. if you are deploying this site to a
# sub_directory, you must set it. For instance, your blog will
# be hosted on 'http://some-domain.com/blog', you have to set
# root_path="/blog", else, if you are deploying this site right
# under the server(even a sub_domain), do nothing, just leave
# here blank: "". But, note that when in localhost, your site
# will run from root regadless of 'root_path', so you must run
# `lilac build` before deploying this site to remote server.
root_path = ""

[blog]
# What is your blog's name?
name = "Make Difference"

# What is your blog about?
description = "Here is your blog's description"

# your blog's url(ends without '/'). This url is will only used
# in feed generation. If you don't have one,  leave here blank.
url = "http://your-domain.org"

# which theme to use?
theme = "classic"

[author]
name = "me"
email = "me@some.com"  # your email address

[disqus]
# your disqus's short name for this blog
shortname = "your-disqus-short-name"

[theme]  # you can reset theme's default configuration here
